document.writeln("<marquee direction=\"left\"><img src=\"http://p0.meituan.net/dptrust/d1ff56b5b4dcb6343d07344ee4270508121.png\" width=\"100\" height=\"1\"><b><font style=\"font-size: 12px; color: #aaaaaa\">听音乐不戴耳机，就是耍流氓 ...</font></b><img src=\"http://p0.meituan.net/dptrust/d1ff56b5b4dcb6343d07344ee4270508121.png\" width=\"100\" height=\"1\"><a href=\"/dy/\"><b><font style=\"font-size: 13px; color: #999999\">➛➛  电影频道入口</font></b></a></marquee>");
document.writeln("<div class=\"text part1\">");
document.writeln("		<div>");
document.writeln("			<span class=\"letter\"><div class=\"character\"><img src=\"http://p0.meituan.net/dptrust/22b438b1a86a2980c4f1f2dcbcc35fde40533.png\" width=\"90\" height=\"50\"></div> <span></span></span>");
document.writeln("			<span class=\"letter\"><div class=\"character\"><img src=\"http://p0.meituan.net/dptrust/27e16b857f9399b063db81893ef4cbd774469.png\" width=\"90\" height=\"45\"></div> <span></span></span>");
document.writeln("			<span class=\"letter\"><div class=\"character\"><img src=\"http://p0.meituan.net/dptrust/a9b0f6e8056bb3fdef7b45f819cb309966237.png\" width=\"45\" height=\"35\"></div> <span></span></span>");
document.writeln("			<span class=\"letter\"><div class=\"character\"><img src=\"http://p0.meituan.net/dptrust/22b438b1a86a2980c4f1f2dcbcc35fde40533.png\" width=\"6\" height=\"6\"></div> <span></span></span>");
document.writeln("			<span class=\"letter\"><div class=\"character\"><img src=\"http://p0.meituan.net/dptrust/d2d6727c55a26cf99687a3ac2f8cb4e859255.png\" width=\"25\" height=\"18\"></div> <span></span></span>");
document.writeln("		</div>");
document.writeln("	</div>    ");
document.writeln("	<span class=\"bio\">");
document.writeln("        <span style=\"transition-delay:2s\" class=\"emphasis\">我</span>");
document.writeln("        <span style=\"transition-delay:.5s\">喜欢</span>");
document.writeln("        <span style=\"transition-delay:1s\">天空</span>");
document.writeln("        <span style=\"transition-delay:1.5s\">喜</span>");
document.writeln("        <span style=\"transition-delay:2s\">欢</span>");
document.writeln("        <span style=\"transition-delay:2.5s\">大</span>");
document.writeln("        <span style=\"transition-delay:3s\">海</span>");
document.writeln("        <span style=\"transition-delay:3.5s\"></span>");
document.writeln("		<span style=\"transition-delay:4s\">更</span>");
document.writeln("        <span style=\"transition-delay:4.5s\"  class=\"emphasis\">喜欢</span>");
document.writeln("        <span style=\"transition-delay:5s\">有品味</span>");
document.writeln("		<span style=\"transition-delay:5.5s\">的</span>");
document.writeln("		<span style=\"transition-delay:6s\"  class=\"emphasis\">你</span>");
document.writeln("    </span>");
document.writeln("    <ul>");
document.writeln("    </ul>");
document.writeln("</div>");
document.writeln("<div class=\"footer\">");
document.writeln("  <a target=\"_self\"rel=\"nofollow\">&copy; 2019 Make By meiliwuya</a>");
document.writeln("</div>");